name: WorldSchematics3
description: Spawns .schematics into newly generated chunks.
version: ${project.version}
author: Optic_Fusion1
main: worldschematics.WorldSchematics
api-version: 1.18
load: POSTWORLD
depend: [WorldEdit]
softdepend: [MythicMobs, ItemsAdder]

commands:
  worldschematics:
    description: The main worldschematics Command
    permission: worldschematics.admin
  spawnstructure:
    description: Spawn a structure
    permission: worldschematics.admin

permissions:
  worldschematics.*:
    description: Gives access to all worldschematics commands
    children:
      worldschematics.admin: true
  worldschematics.admin:
    description: Allows you to use worldschematics Admin commands
    default: op